### ISSUE TITLE
Custom translator - ability to get supported languages using an API

### ISSUE THREAD

**Issue by krisdoodle45** [translate-tools/linguist#105]
Hey, inspired by your code at https://github.com/LibreTranslate/LibreTranslate/issues/55 for LibreTranslate, I tried to extend it to also retrieve the supported languages from the LibreTranslate API. This is what I have so far:

```js
class LibreTranslator {

    static server = "translate.terraprint.co"
    static apiKey = ""

    translate = (text, from, to) => {
        var form = new FormData();
        form.append("q", text);
        form.append("source", from);
        form.append("target", to);
        form.append("format", "text");
        form.append("api_key", this.apiKey);

        return fetch("https://" + this.server + "/translate", {
            credentials: "omit",
            headers: {
                "User-Agent": Navigator.userAgent,
                Accept: "*/*",
                "Accept-Language": "en-US,en;q=0.5",
                "Sec-Fetch-Dest": "empty",
                "Sec-Fetch-Mode": "cors",
                "Sec-Fetch-Site": "same-origin",
            },
            body: form,
            method: "POST",
            mode: "cors",
        })
            .then((r) => r.json())
            .then(({ translatedText }) => translatedText);
    };

    translateBatch = (texts, from, to) =>
        Promise.all(texts.map((text) => this.translate(text, from, to)));

    getLengthLimit = () => 4000;
    getRequestsTimeout = () => 300;
    checkLimitExceeding = (text) => {
        const textLength = !Array.isArray(text) ? text.length : text.reduce((len, text) => len + text.length, 0);

        return textLength - this.getLengthLimit();
    }

    static isSupportedAutoFrom = () => true;

    static getSupportedLanguages = () => {
 	const data = fetch("https://" + this.server + "/languages")
	    .then((r) => r.json())
	    .then((json) => {
		console.log(json.map(languages => languages.code));
	        return json.map(languages => languages.code);
  	    });
    }
}

console.log(LibreTranslator.getSupportedLanguages());
```
The print statement in the function works, but I can't figure out how to make the return statement work. I believe this has something to do with the fact that the fetch statement is asynchronous, and I see this is also the case with the translate and translateBatch functions, but these account for the fact that they return a Promise, whereas getSupportedLanguages doesn't.

Do you think it is possible to fix it in this code block, or is there a change needed in the way getSupportedLanguages is handled in the rest of the code for this functionality?

**Comment by vitonsky** [comment]
`getSupportedLanguages` should return `string`, not a `Promise<string>`

You can just copy array.

This API design is necessary to read translator metadata instantly (not async) and to select most suite translator from list of translators

**Comment by vitonsky** [comment]
You can look at GoogleTranslator as reference implementation of Translator https://github.com/translate-tools/core/blob/master/src/translators/GoogleTranslator/index.ts

**Comment by krisdoodle45** [comment]
Thanks for the response, it was fun to try out

**Comment by vitonsky** [comment]
I've parsed this url, you can just insert this languages list:

```js
[
  "en",
  "ar",
  "az",
  "zh",
  "cs",
  "nl",
  "eo",
  "fi",
  "fr",
  "de",
  "el",
  "hi",
  "hu",
  "id",
  "ga",
  "it",
  "ja",
  "ko",
  "fa",
  "pl",
  "pt",
  "ru",
  "sk",
  "es",
  "sv",
  "tr",
  "uk",
  "vi"
]
```
