### ISSUE TITLE
Release 4.0 for Firefox unable install

### ISSUE THREAD

**Issue by wordpure** [translate-tools/linguist#106]
![image](https://user-images.githubusercontent.com/68013962/168414958-a627a15f-960e-48cb-85cf-03e4f8d01ab3.png)

**Comment by wordpure** [comment]
The code in the extension appears to be obfuscated？

![image](https://user-images.githubusercontent.com/68013962/168415141-36bbb8e2-7b6b-4ac8-88a4-7a68fcbea7f5.png)

**Comment by vitonsky** [comment]
How you try to install it?

**Comment by vitonsky** [comment]
> The code in the extension appears to be obfuscated?

Yes. It's how work a [WebPack](https://webpack.js.org/) in production mode to optimize bundle

**Comment by vitonsky** [comment]
Probably we should provide a source maps to users can analyze code

**Comment by wordpure** [comment]
> How you try to install it?

I try to install `firefox.zip` through `About: config` - `Install add-on from file`.

![image](https://user-images.githubusercontent.com/68013962/168424266-62ddda0a-f541-4fce-af4a-5f3a13ce17e3.png)

In addition, I also tried to import it through the `About: debugging#/runtime/this-firefox` - ` load temporary add-on`. Although everything was normal when it was introduced, once the web translation was performed, `background.js` and `Common.js` will report errors.

![image](https://user-images.githubusercontent.com/68013962/168424742-752d2ff3-5465-4456-aebf-6cd2037f9ce8.png)

**Comment by wordpure** [comment]
> Probably we should provide a source maps to users can analyze code

Good idea👍

**Comment by vitonsky** [comment]
This errors is ok. Its just give info about current state. But i will think about handle it.

I understood you about installation process. Thank you for information.
I have to build package for firefox, to allow users install it from file. I will research and do it in near time.

It's may be useful to provide extension for people even when [AMO ban the extension](https://github.com/translate-tools/linguist/issues/101) due-to [lazy moderator](https://twitter.com/rob_vitonsky/status/1524444279573204996)

**Comment by vitonsky** [comment]
To make standalone addon package, i have to sign it. I've have problem https://github.com/mozilla/addons/issues/1413

After solve this problem i could do it.

**Comment by vitonsky** [comment]
@wordpure done. You can found .xpi file on [release page](https://github.com/translate-tools/linguist/releases/tag/v4.0.1)

**Comment by wordpure** [comment]
> You can found .xpi file on [release page](https://github.com/translate-tools/linguist/releases/tag/v4.0.1)

The extension works well, thanks for your work
