### ISSUE TITLE
Repeated language code description in locales/en

### ISSUE THREAD

**Issue by wordpure** [translate-tools/linguist#110]
The codes `nr`  and `nd` in the [English translation file](https://github.com/translate-tools/linguist/blob/master/src/_locales/en/messages.json) have the same description, which is inconvenient. It is recommended to refer to [List of ISO 639-1 codes - Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) , changed to `North Ndebele` and `South Ndebele`。

![图片](https://user-images.githubusercontent.com/68013962/175814799-9ad94fb5-404b-4d66-a67a-8aa5e7683373.png)

![图片](https://user-images.githubusercontent.com/68013962/175815063-a494b389-6d13-4389-91b9-a6716cf09be4.png)

**Comment by vitonsky** [comment]
Fixed. Release with fixed languages will in near 2 weeks. Thanks for improve linguist
