### ISSUE TITLE
What does “Show translation button once for each text selection” means ?

### ISSUE THREAD

**Issue by wordpure** [translate-tools/linguist#114]
I am translating the extension to Chinese, but I don't understand the meaning of the option `Show translation button once for each text selection`.

I tried enabling and disabling this option, but didn't find that it had any effect on the button display.

Can you please provide me with some help?

![图片](https://user-images.githubusercontent.com/68013962/176356789-67c5edfe-fa4f-4585-8824-a7ddf19a03d6.png)

**Comment by vitonsky** [comment]
Steps:
- select text once, wait untill button will appear and then disappear
- try to call this button with no text reselection (for example press shift and click by end of text)

When option is enabled, button will not appear until you will reselect text

**Comment by wordpure** [comment]
Thank you for your operation steps, I have understood the meaning of this option.
