### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by kiencuongpo** [translate-tools/linguist#125]
Can the extension change the font? Fonts included in windows

**Comment by vitonsky** [comment]
What you mean? Change font where?

**Comment by kiencuongpo** [comment]
Change the font in the pop-up.
![image](https://user-images.githubusercontent.com/102970802/177297469-a6353393-664e-4d54-8a39-f6e8158224f1.png)
Change font in settings
![image](https://user-images.githubusercontent.com/102970802/177297662-09068acf-5e23-4fda-a3e5-b6242257da32.png)

**Comment by vitonsky** [comment]
How it could works? And why?

Describe your vision in details please

**Comment by kiencuongpo** [comment]
I don't know how to describe it. I just want to change the font. example Roboto
