### ISSUE TITLE
Context menu doesn't work

### ISSUE THREAD

**Issue by Gersonzao** [translate-tools/linguist#147]
The context menu option doesn't work. Firefox ESR 103.2

**Comment by vitonsky** [comment]
What is the "context menu option"?

Please, describe what you expected and what you actually have

**Comment by Gersonzao** [comment]
I'm sorry for wasting your time, it works perfectly. I meant this option below. I previously didn't see that it was on the "Translation of elected text" category, not on "Page translation"
![image](https://user-images.githubusercontent.com/85644671/193478462-86966872-5db9-4fcb-bb91-70f8576bda85.png)
