### ISSUE TITLE
Add options to disable history logging and to pause logging with no cleaning

### ISSUE THREAD

**Issue by vitonsky** [translate-tools/linguist#151]
- [ ] Option to disable history
- [ ] Option to ignore history from some sources

**Comment by pointydev** [comment]
Would love this option now that I've found your extension, as translation history makes me slightly uncomfortable.

**Comment by vitonsky** [comment]
> Would love this option now that I've found your extension, as translation history makes me slightly uncomfortable.

You're absolutely correct. I will prioritize this feature. As temporary workaround, you may clear history manually until feature will be implemented.
