### ISSUE TITLE
Add optionally popup with original text for page translator

### ISSUE THREAD

**Issue by vitonsky** [translate-tools/linguist#18]
Sometime translates have wrongs which lead to misunderstanding.

We must implement popup with original text, which will show by hover, and maybe only with pressed hotkey.

It should be optionally feature.

**Comment by vitonsky** [comment]
Implement ASAP.

Requseted from https://github.com/translate-tools/linguist/issues/36

**Comment by minshifu** [comment]
Hi,how is the Show Original function going? I am eager to try it.
![图片](https://user-images.githubusercontent.com/5119952/129748020-db50f9f1-bd02-47b3-881a-cfb5e2a3ae56.png)

**Comment by vitonsky** [comment]
@minshifu in near time i will refactor architecture and next goal is a features upgrade

**Comment by minshifu** [comment]
> 
> 
> @minshifu in near time i will refactor architecture (around 1 week) and next goal is a features upgrade from this milestone: https://github.com/translate-tools/linguist/milestone/1

Looking forward to it! 
![图片](https://user-images.githubusercontent.com/5119952/129833159-3c1f4ddc-26a4-478b-8c82-8202af0113f8.png)

**Comment by vitonsky** [comment]
Prototype is done.
- [ ] Use css files instead inline styles
- [ ] Implement delay
- [ ] Fix edge case with structure "div > inline + block + inline" where last item will not shown

**Comment by vitonsky** [comment]
@minshifu hi, it's done, please, checkout new version 2.2.10 and give feedback if you have
