### ISSUE TITLE
Error when building from source.

### ISSUE THREAD

**Issue by BrightXiaoHan** [translate-tools/linguist#224]
Hi!
I build this project from source on m2 mac. 
```
npm  install
npm run build:chrome
```
When I install it on chrome, the error raised
```
Uncaught (in promise) TypeError: Error in invocation of contextMenus.create(object createProperties, optional function callback): Error at parameter 'createProperties': Unexpected property: 'viewTypes'.
```
<img width="746" alt="截屏2023-03-03 22 05 22" src="https://user-images.githubusercontent.com/25839309/222740212-dd6689a9-7b65-458d-83e1-a2a4db6e3f2c.png">

**Comment by vitonsky** [comment]
Fixed
