### ISSUE TITLE
Implement option to start translate full page and show the original text by press Custom Shortcut keys

### ISSUE THREAD

**Issue by ggpoll** [translate-tools/linguist#266]

**Comment by vitonsky** [comment]
Explain your feature request. You want to hotkey to translate page or to show original text?

**Comment by ggpoll** [comment]
Yes,
Keyboard shortcuts
Switch between the translated and the original page

**Comment by ggpoll** [comment]
@vitonsky 
Is it possible to release an updated version of 4.1 in advance?
I like your browser extension very much, it works very well
At the same time, it is very urgent to enhance the enhancement I proposed

**Comment by vitonsky** [comment]
@ggpoll yes, it possible if you will implement this feature. Feel free to open pull request

**Comment by ggpoll** [comment]
Sorry, my expression is wrong, I have no technical ability, I hope you will implement this feature, I am willing to donate for your work, thank you 😀

**Comment by vitonsky** [comment]
@ggpoll i understood you, i'm work on offline translation feature now, but your feature request looks useful, i will implement it as soon as possible.

If you want to donate to Linguist, you can find details here: https://github.com/translate-tools/linguist#donations
I can focus on your feature request if it such important for you that you will pay for it, i appreciate voting by money

Thank you for a feedback

**Comment by Dook1** [comment]
I support this proposal.

**Comment by ggpoll** [comment]
Thank you very much for your hard work, it is very presumptuous to add a question,
It is whether it is possible to add a menu translation button for the right mouse button at the same time - like the one in the picture
![image](https://user-images.githubusercontent.com/130119037/231707958-c0f7b9d6-59f8-428c-bd68-ef36fcf25892.png)

**Comment by vitonsky** [comment]
@ggpoll this feature been implemented in #83 and will appear in next release soon (next week). Stay tune
