### ISSUE TITLE
Several proposals for improvement 

### ISSUE THREAD

**Issue by minshifu** [translate-tools/linguist#36]
Thank you for creating this promising addon. I'd like to offer several proposals to improve on it. 

1. Currently it often fails to automatically translate some webpages. For example, on the following pages(even if "Always translate this language" is ticked):

(1) nasional.tempo.co/read/1491253/pasien-sembuh-covid-19-hari-ini-39-726-orang/full&view=ok
(2) jdih.tabanankab.go.id/berita/159/rapat-koordinasi-satpol-pp-disperindag-dan-dinas-lingkungan-hidup

![图片](https://user-images.githubusercontent.com/5119952/128585828-a6e29f34-5fc6-46f8-af20-37274ef6ce21.png)

2.  Pls allow translation of webpages of any original language into English.This function is important and indispensible, because in many cases webpages are in mixed languages.
 
    In many cases the original language of a webpage is not detected or wrongly detected. For example, the original language of the following webpage is detected as English by your addon and can not be translated, but actually it also contains many Indonesian words.

https://www.linkedin.com/search/results/people/?keywords=menteri%20pendidikan&origin=CLUSTER_EXPANSION&sid=6ld

![图片](https://user-images.githubusercontent.com/5119952/128586529-b772d47c-c911-4a52-9235-0221bc85e2a1.png)

   When I use Chrome browser(with in-built Google Translate function), the original language of the above webpage is not detected because it is in mixed languages. However,the webpage can be translated into English with the Context Menu button as shown by the picture below.  

![图片](https://user-images.githubusercontent.com/5119952/128586686-4f3f238e-e122-4c65-b40b-91df2904075b.png)

(1) The original language of that linkedin page is not detected by Google Translate, because it contains both English and many Indonesian words. So it just shows "Detected Language" instead of any specific language.

![图片](https://user-images.githubusercontent.com/5119952/128586048-dcef7698-e8ec-4b14-a50a-751318472387.png)
![图片](https://user-images.githubusercontent.com/5119952/128586091-5666d0da-ae39-4b07-8a6b-ec72c20ca5ab.png)

(2) But I need to translate the Indonesian words on that page and I can achieve that by using the Context Menu button as shown by the picture below.

![图片](https://user-images.githubusercontent.com/5119952/128586765-24ed3aa0-3129-471c-9363-95620b1018b0.png)

3. Original Text on mouseover. This funciton is also indispensible as shown by the picure below.

Could you pls consider these proposals? Thank you and best regards!

![图片](https://user-images.githubusercontent.com/5119952/128586960-26c2208d-3119-462c-8be7-9fb5cf4600d6.png)

**Comment by vitonsky** [comment]
Thank you for your reports and suggestions, i consider it and will fix in near time.

Do you have some assumptions about cause of first problem with auto detect?  I already fixed a similar problem, and the reason was that lang attrubute set too late. I added one more chech after awaiting load page to fix it.

Popup with original text already in plans, but at this time i not have idea about grouping text for show result. For example i over my mouse on paragrapth from text on your screen, whats text this popup should show? 
 Text of all childs? Then what if user hover on body element? It will show text of all page in popup?

**Comment by vitonsky** [comment]
- [ ] Fix auto detect langs
- [ ] Allow translate page with same language direction

**Comment by vitonsky** [comment]
Done. Check version 2.1.3

You can get it from [releases page](https://github.com/translate-tools/linguist/releases/tag/v2.1.3) of wait few minutes for update from mozilla addons.

Test it and write your feedback about fixes.

Popup with original text will implement later, but in near future

**Comment by minshifu** [comment]
> 
> 
> Thank you for your reports and suggestions, i consider it and will fix in near time.
> 
> Do you have some assumptions about cause of first problem with auto detect? I already fixed a similar problem, and the reason was that lang attrubute set too late. I added one more chech after awaiting load page to fix it.
> 
> Popup with original text [already in plans](https://github.com/translate-tools/linguist/issues/18), but at this time i not have idea about grouping text for show result. For example i over my mouse on paragrapth from text on your screen, whats text this popup should show?
> Text of all childs? Then what if user hover on body element? It will show text of all page in popup?

Thank you for your kind feedback. 

1) As for your first question, sorry I am a layman when it comes to coding and programming. So I cannot offer any help with this.

2) I think original text shoud be shown paragraph by paragraph. Actually the following screenshot is from another translation addon S3.Translator. Its Original Text Popup function is very good. When that addon is used, original text will be shown paragraph by paragraph or even sentence by sentence as shown by the picture below. The shortcomings of that addon are that it fails to automatically translate many webpages and the offical Google Translate webpage often pops out. Perhaps you could refer to that addon for the Original Text Popup function. 
       Best regards!

![图片](https://user-images.githubusercontent.com/5119952/128598425-70ca317e-6550-47c6-8fde-53bb839ad664.png)

**Comment by minshifu** [comment]
> 
> 
> Done. Check version 2.1.3
> 
> You can get it from [releases page](https://github.com/translate-tools/linguist/releases/tag/v2.1.3) or wait few minutes for update from mozilla addons.
> 
> Test it and write your feedback about fixes.
> 
> Popup with original text will implement later, but in near future

 So far the Auto Detection and Translation funcion works well.  But the Same Language Translation function does not work. 
Although the blue button can be clicked now, the Indonesian words on the linkedin page fails to be translated into English.
      Thank you and Best regards!

https://www.linkedin.com/search/results/people/?keywords=menteri%20pendidikan&origin=CLUSTER_EXPANSION&sid=6ld

![图片](https://user-images.githubusercontent.com/5119952/128599215-9390ebcd-a8a8-49bf-a633-6efa95781a06.png)

**Comment by vitonsky** [comment]
Try use "auto detect" in languages list. Is it work for your case?

**Comment by minshifu** [comment]
> 
> 
> Try use "auto detect" in languages list. Is it work for your case?

Hi, so far the Auto Detection function works well. But the Same Language Translation function does not work on the following page.  

https://www.linkedin.com/search/results/people/?keywords=menteri%20pendidikan&origin=CLUSTER_EXPANSION&sid=6ld

**Comment by vitonsky** [comment]
Translate behavior depends on translation service modules. One module can translate mixed languages, when other can't.

We should not change this behavior to avoid convoluted logic. Site define page language as "english", then we should suggest english even it it not that actually.

We could add option which will detect cases when language set by page is different from actual text on the page and in this case set default language as "undetected" and suggest auto detection if translator support this feature and language which page set otherwise.

What you think about it? This option is would satisfy you?

**Comment by minshifu** [comment]
> 
> 
> Translate behavior depends on translation service modules. One module can translate mixed languages, when other can't.
> 
> We should not change this behavior to avoid convoluted logic. Site define page language as "english", then we should suggest english even it it not that actually.
> 
> We could add option which will detect cases when language set by page is different from actual text on the page and in this case set default language as "undetected" and suggest auto detection if translator support this feature and language which page set otherwise.
> 
> What you think about it? This option is would satisfy you?

I tried the "Auto Detect" just now. So far it works great. Thank you!

**Comment by vitonsky** [comment]
I don't sure that you really want enable option for remember language.

Pages usually have dynamic content and you will have to change language even more often. Even if direction remember functional will bind to domain

But i make issue for feature which can be useful for you: https://github.com/translate-tools/linguist/issues/37

What you think? Is it can satisfy you?

**Comment by minshifu** [comment]
> 
> 
> I don't sure that you really want enable option for remember language.
> 
> Pages usually have dynamic content and you will have to change language even more often. Even if direction remember functional will bind to domain
> 
> But i make issue for feature which can be useful for you: #37
> 
> What you think? Is it can satisfy you?

Thank you so much. What I mean is enabling the addon to remember the choice of "Auto Detect" not a certain language. So far the addon works great. I will continue to try it and offer my thoughts here. Hope the future Original Text Popup function will be similar to that of addon S3.Translator.  Best regards!

**Comment by vitonsky** [comment]
You know, maybe the remember "auto detect" it is not bad function. I will think about it.

Thank for your contribution. In future if you want report or suggest something more, create new issue to maintain cleanliness
