### ISSUE TITLE
Show button in search bar

### ISSUE THREAD

**Issue by aaronliu0130** [translate-tools/linguist#388]
![screenshot showing rightmost part of search bar showing a translate icon and a bookmark icon](https://github.com/translate-tools/linguist/assets/11874211/88761aae-7ccd-48b5-a983-e660c61d2a2c)
Some extensions like <https://github.com/FilipePS/Traduzir-paginas-web> put the button in the search bar. Could this extension do something similar?

**Comment by vitonsky** [comment]
Yes, this is possible, but only for a firefox. Why you wants to have this button and whats feature it should have?

**Comment by aaronliu0130** [comment]
To host the extension itself (it could be an option) and glow when the page has been translated. I also just feel off on putting extra icons in the extensions' space in the toolbar.

**Comment by vitonsky** [comment]
I see the potential, let's develop an idea.

Suggested behavior make sense to save space on extensions bar and to not add yet another icon.
But how users will start a page translation with no extension button on a bar? Think deep about it.

Probably some users would use a hotkeys to toggle page translation, but in this case a icon in omnibox not necessary at all.

**Comment by aaronliu0130** [comment]
Same example with the other extension I've mentioned above:
![omnibar button with modal open](https://github.com/translate-tools/linguist/assets/11874211/009d0155-decf-4d71-bfc2-579073aa4ccf)

**Comment by vitonsky** [comment]
I see a potential in your idea, but i can't start development just to copy any behavior of another extension, it is not work like that.

If you really needed this feature - think deep about why you needs this feature and answer yourself for those questions:
- why i want this feature?
- what problem i have with no this feature?
- how this feature will solve my problem?
- how exactly this feature will works for me and for another people on other browsers and OS with another workflow
- is i sure this feature is still useful?

When you will done with a reflection, come back and add more details

**Comment by aaronliu0130** [comment]
I don't need it that much.
