### ISSUE TITLE
Features and improvements

### ISSUE THREAD

**Issue by realgooseman** [translate-tools/linguist#396]
Hi @vitonsky and other contributors,

Best translating extension out there, I use it daily. But I'd suggest some improvements : 

- Dark theme : ideally for all Linguist pages/pop-ups. But pop-up only is good too (Prioritized, to prevent eye strain at night)
- More translation options (LibreTranslate, Lingva, DeepL with API key,...)
- Adding a button on the pop-up to copy all translated text to clipboard (for now there only is a TTS and bookmark button)
- Built-in dictionary that gives selected word definition, pronunciation,... with the translation pop-up (Wiktionary, TheFreeDictionary,..)

I've seen there are already open issues for some improvements I mentioned, are these features considered or being worked on ?

**Comment by vitonsky** [comment]
@realgooseman hi, you can use custom translators right now, check the https://github.com/translate-tools/linguist-translators.

We have issue #86 for a dark theme, but i no have enough time for now to work on it.

Built-in dictionary it's good idea, you can create issue for it.

> Adding a button on the pop-up to copy all translated text to clipboard (for now there only is a TTS and bookmark button)

You can check the #301 and comment there:
- where you want to have a button to copy
- how this button should works
- help us to choose place for the button

**Comment by realgooseman** [comment]
Great, thanks for the clarification. I will create an issue for the Built-in dictionary feature.
