### ISSUE TITLE
Please add the possibility of offline translation from English to Russian.

### ISSUE THREAD

**Issue by Katran-399A** [translate-tools/linguist#398]
Please add the possibility of offline translation from English to Russian.

**Comment by vitonsky** [comment]
You can do it right now.

![image](https://github.com/translate-tools/linguist/assets/86191922/4b3902a2-6deb-4f89-b6d3-8d0075b34299)

Just pick "Bergamot - Offline translator" in settings

![image](https://github.com/translate-tools/linguist/assets/86191922/fd1e0f16-bccb-4b61-ad9c-7b4ae9f543ef)

**Comment by vitonsky** [comment]
I close the question. Feel free to reopen if it did not solved your problem
