### ISSUE TITLE
Listing on Firefox Android extension store

### ISSUE THREAD

**Issue by nghduc97** [translate-tools/linguist#418]
Firefox Android now support installing extensions without developer settings again, but Linguist is not listed. Can the owner enable it for Android install as well?

Extension store: https://addons.mozilla.org/en-US/android/

**Comment by vitonsky** [comment]
@nghduc97 i've updated supported versions, now Linguist should be visible in this list. Could you please check to confirm

**Comment by nghduc97** [comment]
Confirmed, it can be installed from the store now, thanks 👌

**Comment by vitonsky** [comment]
Thank you
