### ISSUE TITLE
Update CodeQL version in CI config

### ISSUE THREAD

**Issue by vitonsky** [translate-tools/linguist#428]
CI logs have a [warning](https://github.com/translate-tools/linguist/actions/runs/8961247420)

> This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

We should update CodeQL vesrion in `codeql-analysis.yml`

**Comment by hamirmahal** [comment]
Hmm... What're your thoughts on removing `codeql-analysis.yml` altogether, and enabling it via the repository settings, instead?

![image](https://github.com/translate-tools/linguist/assets/43425812/3c7e3792-b114-4342-b8b7-8f288144ef7e)

https://github.com/hamirmahal/FilmFinder/ doesn't have a `codeql-analysis.yml` file, but [it still has CodeQL checks run occasionally, anyway](https://github.com/hamirmahal/FilmFinder/actions/runs/8921494327/job/24501709311).

![image](https://github.com/translate-tools/linguist/assets/43425812/195146e2-88b8-4ab6-86a6-30509f8a92b9)

https://github.com/hamirmahal/FilmFinder/tree/main/.github/workflows

**Comment by vitonsky** [comment]
I just found out that we can run CodeQL with no config and it will auto detect most suitable config. I will try it on days, thanks!

**Comment by hamirmahal** [comment]
You're welcome!
