### ISSUE TITLE
Update required node version to 20

### ISSUE THREAD

**Issue by vitonsky** [translate-tools/linguist#429]
CodeQL action have [warning](https://github.com/translate-tools/linguist/actions/runs/8961247420)

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, github/codeql-action/init@v1, github/codeql-action/autobuild@v1, github/codeql-action/analyze@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Currently the project uses node version 14. We have to update node to version 20, test all works fine, fix a potential problems and update engines in `packages.json`. Also, let's mention dev requirements in the docs, we should add info about node version, docker and another tools that are required to make build

**Comment by hamirmahal** [comment]
Is there a way to benchmark performance currently? It might be interesting to see speed changes after upgrading to `node` 20.

**Comment by vitonsky** [comment]
I think we currently no have benchmarks. We should update node just because 14 version is deprecated and do not supported anymore. I will try to add more unit tests in future, it will be useful additionally for measure performance between node versions too.

Potentially, we may have a problems with build the code with a new node version

**Comment by hamirmahal** [comment]
How do you test `./Dockerfile` and `thirdparty/bergamot/Dockerfile`?

**Comment by vitonsky** [comment]
> How do you test `./Dockerfile` and `thirdparty/bergamot/Dockerfile`?

We just run a command `make buildAll` that build all things. If this command fails, then we have broken code
