### ISSUE TITLE
Use in Web Application

### ISSUE THREAD

**Issue by lynxionxs** [translate-tools/linguist#438]
Can this be used in a Javascript Web App instead of a chrome extension. Like in a NuxtJS or NextJS web app ?

**Comment by vitonsky** [comment]
> Can this be used in a Javascript Web App instead of a chrome extension. Like in a NuxtJS or NextJS web app ?

What you mean with your question? Linguist is an standalone full featured application. If your question is "is it possible to embed a Linguist into my application" then answer probably no, by the same reasons you can't embed twitter or Cyberpunk 2077.

But you we have NPM package https://github.com/translate-tools/domtranslator used by Linguist, that let you handle DOM elements for translation. And also we have a NPM package https://github.com/translate-tools/core used by Linguist, that provide translators implementations. So, you may use this packages to implement your own code for translation on client side.

If you looking for an embedded solution for translate DOM, you may create it yourself as described above, or you may contact me with email if you need help with implementation or deep consulting. If you are ready to implement it yourself, feel free to create issues in mentioned repositories about any bugs or documentation related questions.

**Comment by lynxionxs** [comment]
@vitonsky thanks. I just thought it would be good to have a Linguist standalone version to install via npm. So a person have a choice to install the chrome extension or have it provided by a Web app, where it's integrated in the app by the developer. I will play around with your suggestions. Thanks.
