### ISSUE TITLE
6.0 version not work on chrome 126.0.6478.62

### ISSUE THREAD

**Issue by TUGOhost** [translate-tools/linguist#468]
# My Case
![image](https://github.com/translate-tools/linguist/assets/28786059/234b413c-f35b-4fc4-97a5-4241318c9974)
chrome version:
![image](https://github.com/translate-tools/linguist/assets/28786059/04049324-3dbf-4d44-8b93-91deb4470a41)
linguist plugin version:
![image](https://github.com/translate-tools/linguist/assets/28786059/4d9d2d6d-ec74-4d65-ab31-69200aadb02c)
---
before 6.0 version I can use it.

**Comment by vitonsky** [comment]
I debug this problem currently, probably this problem due to a new mechanism on background worker that may be terminated any time.

Please give more details you note about this problem. If you close browser, wait 10 seconds, then open it and try to use Linguist - it works fine?

**Comment by TUGOhost** [comment]
Sorry,I don't know how to debugg chrom plugin.
I click F12 button:
![image](https://github.com/translate-tools/linguist/assets/28786059/b7f843c6-da5c-465d-a19a-1586fc2db5c6)

I tried closing Chrome and waiting 10 seconds, then opening the Linguist plugin and it still doesn't work!

**Comment by vitonsky** [comment]
@TUGOhost what if you close Chrome browser, and then open after 10 seconds? Problem still there?

**Comment by TUGOhost** [comment]
yes, the problem still exists

**Comment by vitonsky** [comment]
> yes, the problem still exists

I still cannot to reproduce the bug, could you provide some info to debug:

- What is your OS and version?
- Which translator you used last time (if you know)
- Go to `chrome://extensions/`, then click "Developer mode", then click "service worker" and send screenshot of new window
  ![image](https://github.com/translate-tools/linguist/assets/86191922/1c40bcd1-3f8a-4b9b-bdc1-fa21373d46a5)
- If it possible, could you record your screen (you may use [OBS studio](https://obsproject.com/)) where you close browser, then wait 10-20 seconds, then open Chrome, open some site and click by Linguist icon

**Comment by TUGOhost** [comment]
-  OS version: Windows 11 home editor

I click `chrome://extensions/` -> `Developer mode`  -> `service worker`,then show:
![image](https://github.com/translate-tools/linguist/assets/28786059/c8c21ca1-699d-4695-afd5-1a209f3072d8)

video:



https://github.com/translate-tools/linguist/assets/28786059/c31a1fbc-731a-4edb-9a5a-c1f67fc8733a

**Comment by vitonsky** [comment]
@TUGOhost i think we may have problem with config migrations.

Could you sent your config data, to let me debug a problem:
- click "service worker" again as in instruction above
- paste next code: `await chrome.storage.local.get().then(data=> JSON.stringify(data))` and press enter
- copy result string and sent it here or to email linguist-support@vitonsky.net

String that you will copy may contains last texts that you tried to translate, so you may sent it with email to don't disclosure a sensetive data

**Comment by vitonsky** [comment]
@TUGOhost if you create a new chrome profile and install Linguist there is it will work fine?

**Comment by TUGOhost** [comment]
> * click "service worker" again as in instruction above
> * paste next code: `await chrome.storage.local.get().then(data=> JSON.stringify(data))` and press enter
> * copy result string and sent it here or to email [linguist-support@vitonsky.net](mailto:linguist-support@vitonsky.net)

Don't worry, no sensitive content

![image](https://github.com/translate-tools/linguist/assets/28786059/d7298e6e-ce07-4131-9123-afbce5ee998b)

```text
'{"PageTranslationStorage":{"optionsSpoilerState":false},"PopupWindowStorage":{"activeTab":{"translatePage;translateText":"translateText","translateText":"translateText"}},"TextTranslatorStorage":{"from":"en","to":"zh","translate":{"originalText":"IDAPython was created in 2004 . It was a joint ef f ort by Gergely Erdelyi and Ero Carrera. Their goal was to combine the power of Python with the analysis automation of IDA’s IDC C-like scripting language.IDAPython consists of three separate modules. The f irst is idc . It is a compatibility module f or wrapping IDA’s IDC f unctions. The second module is idautils . It is a high level utility f unctions f or IDA. The third module is idaapi . It allows access to more low level data. This data could be classes used by IDA.","translatedText":"IDAPython 创建于 2004 年。 这是 Gergely Erdelyi 和 Ero Carrera 的共同努力。 他们的目标是将 Python 的强大功能与 IDA 的 IDC C 类脚本语言的分析自动化相结合。IDAPython 由三个独立的模块组成。 第一个是idc。 它是一个兼容模块，用于包装 IDA 的 IDC 功能。 第二个模块是 idautils 。 它是 IDA 的高级实用函数。 第三个模块是 idaapi 。 它允许访问更多低级数据。 该数据可能是 IDA 使用的类."}},"appConfig":{"history":{"enabled":true}},"migrationsInfo":{"dataVersions":{"ConfigStorage":6,"PopupWindowStorage":1,"TextTranslatorStorage":3,"TranslatorCache":3,"autoTranslationPreferences":1},"version":1},"recentUsedLanguages":["zh","auto"]}'
```

**Comment by TUGOhost** [comment]
> @TUGOhost if you create a new chrome profile and install Linguist there is it will work fine?

I just uninstalled the Lingust plugin and reinstalled it and it worked again!

**Comment by vitonsky** [comment]
@TUGOhost thanks for your report, problem now fixed, a new version with fix will be published soon.
Your report are pretty detailed and been important to debug a problem 👍
