### ISSUE TITLE
The extension is displayed incorrectly if it opens above the browser

### ISSUE THREAD

**Issue by Doaxan** [translate-tools/linguist#512]
If the extension doesn't have enough space to open down, it opens up and displays a white screen.
firefox-developer-edition 131.0b5 (64-bit) with wayland session

![image](https://github.com/user-attachments/assets/8933a5e9-9bcd-4482-aed4-dbbf1a7703c4)

**Comment by vitonsky** [comment]
It looks as problem with browser, not with Linguist. I just checked, it works fine for me, so I temporary mark as unconfirmed

**Comment by Doaxan** [comment]
Indeed, in the X11 session of KDE everything works as expected, apparently I need to create a ticket in bugzilla, thank you!
