### ISSUE TITLE
Add a quick copy feature to the output window of "Text Translation."

### ISSUE THREAD

**Issue by XM-8JD2** [translate-tools/linguist#515]
## What problem you have?
I frequently need to translate words and sentences, and sometimes the content I need to translate is too long, which means I have to scroll down to the bottom of the "Text Translation" window to copy the translation I need.

## Why you need this changes and how this changes will solve your problem?
It can be tedious to repeatedly select the entire translation block, so a button to quickly copy it would save my attention.

## What exactly behavior you expect? Describe as many details as possible
Add a button that allows one-click copying of the translation to the clipboard.
![-01](https://github.com/user-attachments/assets/15513891-7932-41a1-90da-848c1454c3ec)

**Comment by vitonsky** [comment]
It make sense. Related to  #301
