### ISSUE TITLE
[Feature Request] Show simultaneous translations

### ISSUE THREAD

**Issue by Terkyz** [translate-tools/linguist#518]
It would be useful that instead of just showing one translation from my main translation engine, it shows different translations from different engines automatically.

**Comment by vitonsky** [comment]
What is your use case?

**Comment by Terkyz** [comment]
Not always the translation of an engine is accurate, or sometimes the translation of an engine is not exactly understood, it would be great to be able to read several translations in a row to choose the best one according to the context.

**Comment by vitonsky** [comment]
If we have problem with some translator engine - we should focus on fix problem with those engines, or provide another translator with good quality, not to show all possible translations. So currently this proposal does not make sense by my opinion. You may reasoning in this issue about use cases where this feature would be really useful
