### ISSUE TITLE
Add icon for dark theme

### ISSUE THREAD

**Issue by vitonsky** [translate-tools/linguist#70]
Add icon for dark theme and select contrast icon automatically by default or manually on settings page.

Useful links
- https://stackoverflow.com/a/57795495
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme

**Comment by ai** [comment]
Here is how it looks right now

![Снимок экрана от 2021-11-29 23-01-44](https://user-images.githubusercontent.com/19343/143949857-e78beca4-e478-4464-88bb-aceb38d7ce05.png)

**Comment by vitonsky** [comment]
Have been done in release https://github.com/translate-tools/linguist/releases/tag/v3.0.2

**Comment by e-t-l** [comment]
@vitonsky In dark theme, the Linguist icon is bright yellow. Is it possible to make it white? (either as an update to this extension, or by a some custom userChrome.css styling?)

**Comment by vitonsky** [comment]
> @vitonsky In dark theme, the Linguist icon is bright yellow. Is it possible to make it white? (either as an update to this extension, or by a some custom userChrome.css styling?)

It is technically possible, but it will not be implemented since the colors of Linguist is the design decision.

If you have ideas about colors in Linguist, feel free to make a new issue to explain there your idea and proposed changes.

By the way, we think about concepts for new Linguist logo, so if you have any ideas, you are welcome
