### ISSUE TITLE
Translate selected text

### ISSUE THREAD

**Issue by ai** [translate-tools/linguist#78]
Other translation extensions have useful feature of translating small phrases by selecting them in text and choose Trans;late Selected Text in right-lick menu

**Comment by ai** [comment]
I found a way to do it with icon, but I prefer right-click menu to not change browser UI too much

**Comment by vitonsky** [comment]
Are you mean this scenario?
- select text
- right click and select "translate" in context menu

It's sounds useful

**Comment by ai** [comment]
> Are you mean this scenario?

Yeap

**Comment by vitonsky** [comment]
Have been implement in https://github.com/translate-tools/linguist/pull/82
