### ISSUE TITLE
Make scrollbar thin in components on the page

### ISSUE THREAD

**Issue by zeref-dragneel** [translate-tools/linguist#99]
Custom minimalistinc & slim scrollbar for popup on Linguist
![image](https://s10.gifyu.com/images/Animationa987aa7839f3b305.gif)

**Comment by vitonsky** [comment]
Please, edit your issue, explain what you want in details and add more info about how it should work

**Comment by zeref-dragneel** [comment]
> Please, edit your issue, explain what you want in details and add more info about how it should work

Do you think using custom scrollbars are a good idea?

**Comment by vitonsky** [comment]
> Do you think using custom scrollbars are a good idea?

I think no, because we should use native scrollbars for user platform.
I may make scrollbar for popups on the pages is thin, but not custom.

Which browser you are using?

Is you want to use custom scrollbar? If yes, then how it may be implemented as option? It's can't be enabled by default.

**Comment by zeref-dragneel** [comment]
>I may make scrollbar for popups on the pages is thin, but not custom.

Okay. that’s acceptable
